CREATE TABLE IF NOT EXISTS contracts (
    CONTRACT_ID VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255),
    CONTRACT_CREATED_AT TIMESTAMP,
    STATUS VARCHAR(255) NOT NULL,
    COMPLETION_DATE TIMESTAMP,
    IS_DELETED BOOLEAN NOT NULL,
    RECEIVED_AT TIMESTAMP NOT NULL
);