CREATE TABLE IF NOT EXISTS invoices (
    INVOICE_ID VARCHAR(255) NOT NULL,
    CONTRACT_ID VARCHAR(255) NOT NULL,
    AMOUNT INT NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    IS_EARLY_PAID BOOLEAN NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    RECEIVED_AT TIMESTAMP NOT NULL
);